# Generated by Django 4.0.1 on 2022-02-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Salary', models.IntegerField(max_length=5)),
                ('Department', models.CharField(max_length=50)),
            ],
        ),
    ]
